# This file was generated by GoReleaser. DO NOT EDIT.
cask "bdinfo" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "8d63e3fd4cff3d3438c40bcf8c006114388820bb3f118c67b25bd1b18b73ed1f"
      url "https://github.com/autobrr/go-bdinfo/releases/download/v#{version}/bdinfo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "31b414300a5745acaacbd99a4ebc5ce2623aa7614986f41be51570c712f692ba"
      url "https://github.com/autobrr/go-bdinfo/releases/download/v#{version}/bdinfo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "75cffac8adf3c1c971aaffb7843edd053a2d275814439bfd4868ba7774080feb"
      url "https://github.com/autobrr/go-bdinfo/releases/download/v#{version}/bdinfo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "37d389107894589a54e37e0d9f503c8f8c53960614714ee8095f06bdb9ec9437"
      url "https://github.com/autobrr/go-bdinfo/releases/download/v#{version}/bdinfo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bdinfo"
  desc "Go rewrite of BDInfo."
  homepage "https://github.com/autobrr/go-bdinfo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bdinfo"

  # No zap stanza required

end
